{{ config(materialized='view') }}

SELECT
    O_ORDERKEY AS ORDER_ID,
    O_ORDERDATE AS LOAD_DATE,
    'SNOWFLAKE_SAMPLE' AS RECORD_SOURCE,
    O_TOTALPRICE AS TOTAL_PRICE,
    O_ORDERSTATUS AS ORDER_STATUS
FROM {{ source('tpch', 'orders') }}
WHERE O_ORDERDATE <= DATE('1992-01-31')
