{{ config(materialized='view') }}

SELECT
    {{ hash_entity('O_ORDERKEY') }} AS ORDER_PK,
    
    O_ORDERKEY AS ORDER_ID,
    O_ORDERDATE AS LOAD_DATE,
    'SNOWFLAKE_SAMPLE' AS RECORD_SOURCE,
    O_ORDERDATE AS ORDER_DATE,
    O_ORDERPRIORITY AS ORDER_PRIORITY,
    O_CLERK,
    O_TOTALPRICE AS TOTAL_PRICE,
    O_ORDERSTATUS AS ORDER_STATUS,

    {{ hash_diff(['O_ORDERDATE', 'O_CLERK', 'O_ORDERPRIORITY']) }} AS HASHDIFF_DETAILS,

    {{ hash_diff(['O_TOTALPRICE', 'O_ORDERSTATUS']) }} AS HASHDIFF_STATUS

FROM {{ source('tpch', 'orders') }}
WHERE O_ORDERDATE <= DATE('1992-01-31')
