{{ config(materialized='view') }}

SELECT
    MD5(CAST(O_ORDERKEY AS VARCHAR)) AS ORDER_PK,
    O_ORDERKEY AS ORDER_ID,
    O_ORDERDATE AS LOAD_DATE,
    'SNOWFLAKE_SAMPLE' AS RECORD_SOURCE,
    O_ORDERDATE AS ORDER_DATE,
    O_ORDERPRIORITY AS ORDER_PRIORITY,
    O_CLERK,
    O_TOTALPRICE AS TOTAL_PRICE,
    O_ORDERSTATUS AS ORDER_STATUS,

    MD5(
        CAST(O_ORDERDATE AS VARCHAR)
        || CAST(O_CLERK AS VARCHAR)
        || CAST(O_ORDERPRIORITY AS VARCHAR)
    ) AS HASHDIFF_DETAILS,

    MD5(
        CAST(O_TOTALPRICE AS VARCHAR)
        || CAST(O_ORDERSTATUS AS VARCHAR)
    ) AS HASHDIFF_STATUS

FROM {{ source('tpch', 'orders') }}
WHERE O_ORDERDATE <= DATE('1992-01-31')