name: 'snowflake_analytics'
version: '1.0.0'
config-version: 2

profile: 'snowflake_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    raw_vault:
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: ignore
      +schema: raw_vault

      hubs:
        +tags: ["raw_vault", "hub"]
      links:
        +tags: ["raw_vault", "link"]
      sats:
        +tags: ["raw_vault", "sat"]

    business_vault:
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: ignore
      +schema: business_vault
      +tags: ["business_vault"]

    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]

seeds:
  snowflake_analytics:
    +schema: staging
    +tags: ["seed"]
