models:
  snowflake_analytics:
    snowflake_analytics:
      
      staging:
        +materialized: view
        +schema: staging
        +tags: ["staging"]

      raw_vault:
        +materialized: incremental
        +schema: raw_vault
        
        hubs:
          +tags: ["raw_vault", "hub"]
        links:
          +tags: ["raw_vault", "link"]
        sats:
          +tags: ["raw_vault", "sat"]

      marts:
        +materialized: table
        +schema: marts
        +tags: ["marts"]
      
      business_vault:
        +materialized: incremental
        +schema: business_vault
        +tags: ["business_vault"]
