{{ config(materialized='table') }}

WITH hub AS (
    SELECT CUSTOMER_PK FROM {{ ref('hub_customer') }}
),
sat_invar AS (
    SELECT CUSTOMER_PK, LOAD_DATE
    FROM {{ ref('sat_customer_invar') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_PK ORDER BY LOAD_DATE DESC) = 1
),
sat_var AS (
    SELECT CUSTOMER_PK, LOAD_DATE
    FROM {{ ref('sat_customer_var') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_PK ORDER BY LOAD_DATE DESC) = 1
),
sat_biz AS (
    SELECT CUSTOMER_PK, LOAD_DATE
    FROM {{ ref('sat_customer_business') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_PK ORDER BY LOAD_DATE DESC) = 1
)

SELECT
    h.CUSTOMER_PK,
    COALESCE(i.LOAD_DATE, CAST('1900-01-01' AS DATE)) AS SAT_INVAR_LOAD_DATE,
    COALESCE(v.LOAD_DATE, CAST('1900-01-01' AS DATE)) AS SAT_VAR_LOAD_DATE,
    COALESCE(b.LOAD_DATE, CAST('1900-01-01' AS DATE)) AS SAT_BIZ_LOAD_DATE,
    CURRENT_TIMESTAMP() AS PIT_LOAD_DATE
FROM hub h
LEFT JOIN sat_invar i ON h.CUSTOMER_PK = i.CUSTOMER_PK
LEFT JOIN sat_var v ON h.CUSTOMER_PK = v.CUSTOMER_PK
LEFT JOIN sat_biz b ON h.CUSTOMER_PK = b.CUSTOMER_PK
