{{ config(materialized='view') }}

SELECT
    MD5(CAST(O_ORDERKEY AS VARCHAR)) AS ORDER_PK,

    O_ORDERKEY AS ORDER_ID,

    O_ORDERDATE AS LOAD_DATE,
    'SNOWFLAKE_SAMPLE' AS RECORD_SOURCE,

    O_TOTALPRICE,
    O_ORDERSTATUS

FROM {{ source('tpch', 'orders') }}
WHERE O_ORDERDATE <= DATE('1992-01-31')
